// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Localization Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;

namespace LocalizationEditor
{
    public class LESampleKeys
    {
        public static string SampleTitle = "SampleTitle";
        public static string LangLabel = "LangLabel";
        public static string GUITextKey = "GUITextKey";
        public static string TextMeshKey = "TextMeshKey";
        public static string FromCodeKey = "FromCodeKey";
        public static string ar = "ar";
        public static string he = "he";
        public static string ur = "ur";
    }
}
